// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leumgpdwnxhwrikkopye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxldW1ncGR3bnhod3Jpa2tvcHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mzg0ODYsImV4cCI6MjA3MzAxNDQ4Nn0.dNgPgGk9fdZ2Em_OdiSkNudcBX7Vmf0lkkaUaSD8Pnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});